import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices, type PartialLangiumSharedServices } from 'langium/lsp';
import { JpipeGeneratedModule, JpipeGeneratedSharedModule } from './generated/module.js';
import { JpipeValidator, registerValidationChecks } from './jpipe-validator.js';
import { JpipeScopeProvider } from './jpipe-scope.js';
import { JpipeImportService } from './jpipe-import.js';
import { JpipeCompletionProvider } from './jpipe-completion.js';
import { JpipeDefinitionProvider } from './jpipe-definition-provider.js';
import { JpipeDocumentSymbolProvider } from './jpipe-symbol-provider.js';
import { JpipeNameProvider } from './jpipe-utils.js';
import { JpipeHoverProvider } from './jpipe-hover-provider.js';
import { JpipeSemanticTokenProvider } from './jpipe-semantic-token-provider.js';
import { JpipeRenameProvider } from './jpipe-rename-provider.js';
import { JpipeCodeActionProvider } from './jpipe-code-action-provider.js';
import { JpipeFormatter } from './jpipe-formatter.js';
import { JpipeLanguageServer } from './jpipe-language-server.js';
import { JpipeServerLogger, type LogLevel } from './jpipe-logger.js';
import { JpipeDocumentValidator } from './jpipe-document-validator.js';
import { JpipeExclusionService } from './jpipe-exclusions.js';
import { JpipeUnificationService } from './jpipe-unification.js';
import { JpipeParserErrorMessageProvider } from './jpipe-parser-errors.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type JpipeAddedServices = {
    validation: {
        JpipeValidator: JpipeValidator
    },
    references: {
        JpipeImportService: JpipeImportService
    },
    logger: JpipeServerLogger,
    exclusions: JpipeExclusionService,
    unification: JpipeUnificationService
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type JpipeServices = LangiumServices & JpipeAddedServices

/**
 * Shared-service overrides.
 *
 * Only the language server itself, so that the code-action capability arrives with its kinds
 * attached rather than as a bare boolean.
 */
const JpipeSharedModule: Module<LangiumSharedServices, PartialLangiumSharedServices> = {
    lsp: {
        LanguageServer: (services) => new JpipeLanguageServer(services)
    }
};

function buildJpipeModule(
    logger: JpipeServerLogger,
    exclusions: JpipeExclusionService,
    unification: JpipeUnificationService
): Module<JpipeServices, PartialLangiumServices & JpipeAddedServices> {
    return {
        parser: {
            ParserErrorMessageProvider: () => new JpipeParserErrorMessageProvider()
        },
        validation: {
            JpipeValidator: (services) => new JpipeValidator(services),
            DocumentValidator: (services) => new JpipeDocumentValidator(services, exclusions, logger)
        },
        references: {
            ScopeProvider: (services) => new JpipeScopeProvider(services),
            JpipeImportService: (services) => new JpipeImportService(services),
            NameProvider: () => new JpipeNameProvider()
        },
        lsp: {
            DefinitionProvider:     (services) => new JpipeDefinitionProvider(services),
            DocumentSymbolProvider: (services) => new JpipeDocumentSymbolProvider(services),
            CompletionProvider:     (services) => new JpipeCompletionProvider(services),
            HoverProvider:          (services) => new JpipeHoverProvider(services),
            SemanticTokenProvider:  (services) => new JpipeSemanticTokenProvider(services),
            RenameProvider:         (services) => new JpipeRenameProvider(services),
            // Binding this is all it takes: `startLanguageServer` advertises
            // `codeActionProvider` from the presence of the service.
            CodeActionProvider:     (services) => new JpipeCodeActionProvider(services),
            // Likewise `documentFormattingProvider` and `documentRangeFormattingProvider`.
            Formatter:              () => new JpipeFormatter()
        },
        logger: () => logger,
        exclusions: () => exclusions,
        unification: () => unification
    };
}

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @param logLevel Controls verbosity of the language server log (default: 'info')
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createJpipeServices(context: DefaultSharedModuleContext, logLevel: LogLevel = 'info'): {
    shared: LangiumSharedServices,
    Jpipe: JpipeServices
} {
    const logger = new JpipeServerLogger(logLevel);
    const exclusions = new JpipeExclusionService(logger);
    const unification = new JpipeUnificationService();
    const shared = inject(
        createDefaultSharedModule(context),
        JpipeGeneratedSharedModule,
        JpipeSharedModule
    );
    const Jpipe = inject(
        createDefaultModule({ shared }),
        JpipeGeneratedModule,
        buildJpipeModule(logger, exclusions, unification)
    );
    shared.ServiceRegistry.register(Jpipe);
    registerValidationChecks(Jpipe);
    // Wired here rather than in the service constructor, where reaching for DocumentBuilder
    // during injection would risk a dependency cycle.
    shared.workspace.DocumentBuilder.onUpdate(() => Jpipe.references.JpipeImportService.invalidateGlobCache());
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Jpipe };
}
