# workflow to produce the VS code extension

name: Build VS Code extension

on: 
  push: 
  pull_request:
  workflow_dispatch:  # Can be triggered manually

env:
  NODEJS_VERSION: '20.19.2'

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{env.NODEJS_VERSION}}'

      - name: Install vsce to package code
        run: |
          npm install
          npm install -g @vscode/vsce
      
      - name: Package extension as VSIX artefact
        run: |
          cd packages/extension
          vsce package -o jpipe-extension.vsix
      
      - name: Upload VSIX artefact
        uses: actions/upload-artifact@v4
        with:
          name: jpipe-extension.vsix
          path: jpipe-extension.vsix
    
